apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress-controller 
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/binoopnanu/argo-app
    targetRevision: HEAD
    path: infra/nginx-controller
  destination: 
    server: https://kubernetes.default.svc
    namespace: nginx-ingress

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
